package com.soho.sohoapp.live.ui.navigation

enum class NavigationPath {
    SPLASH,
    PRE_ACCESS,
    SIGNIN,
    SIGNUP,
    FORGET_PW,
    HOME,
    SCHEDULED,
    GO_LIVE,
    VIDEO_LIBRARY,
    PROFILE,
    SET_SCHEDULE,
    GO_LIVE_SUCCESS,
    VIDEO_MANAGE,
    LIVE_CAST_END,
    WEB_VIEW,
    WEB_VIEW_MAIN,
    VIDEO_PLAYER,
    VIDEO_RECORDER,
    VIDEO_EDIT_DETAILS,
    PRE_RECODED_LIST,
    PLAYER,
    REVIEW,
    TEMPLATE,
    SUBSCRIPTION,
    USAGE,
    FORGET_PW_SENT,
    RESET_PASSWORD
}